### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by squiersrobbie** [JoeLudwig/overlay_experiments#1]
My wifes parents have paid someone to torment me with my phone and one of the apps that keeps appearing is GOOGLE VR with this License, over and over no matter how often I delete it. Could you direct me on how to avoid this? Or is this app simply that manipulatable for hackers and bad actors?

**Comment by JoeLudwig** [comment]
This project was an experiment that only ran on Windows. It doesn't have anything to do with what's going on with your phone.

Google VR is part of Android. It's probably coming back when Google pushes a system update.

**Comment by benotter** [comment]
Hey Joe, just to add on to similar reins of relevance, some guy paid my parents to install the Costco app on my Nokia brick phone, can you give me the private keys to your house, or is this repo simply too manipulable to hackers and reverse-good actors?
